otg/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^otgweb/', include('otgweb.urls')),
    url(r'^admin/', admin.site.urls),
]

otgweb/urls.py
from django.conf.urls import url

from . import views

app_name = "otgweb"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^events/$', views.events, name='events'),
    url(r'^events/(?P<event_id>[0-9]+)/$', views.event_detail, name='event_detail'),
    url(r'^vendors/$', views.vendors, name='vendors'),
    url(r'^vendors/(?P<vendor_id>[0-9]+)/$', views.vendor_detail, name='vendor_detail'),
]

otgweb/models.py
from __future__ import unicode_literals

from django.db import models

class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_time = models.DateTimeField()
    place_name = models.CharField(max_length=255)
    end_time = models.DateTimeField()
    fb_graph_id = models.CharField(max_length=255)
    otg_event_id = models.IntegerField(null=True, blank=True)
    vendors = models.ManyToManyField('Vendor', through='Membership')

    def __str__(self):
        return self.name

class Vendor(models.Model):
    name = models.CharField(max_length=255)
    website = models.CharField(max_length=255, null=True, blank=True)
    cuisine = models.CharField(max_length=255, null=True, blank=True)
    logo_url = models.CharField(max_length=255, null=True, blank=True)
    otg_vendor_id = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Membership(models.Model):
    event = models.ForeignKey('Event')
    vendor = models.ForeignKey('Vendor')

    def __str__(self):
        return "Event({}), Vendor({})".format(self.event, self.vendor)

otgweb/views.py
from django.shortcuts import get_object_or_404, render

from datetime import datetime, timedelta
from django.db.models import Case, Count, IntegerField, Sum, When
from django.utils import timezone

from .models import Event, Vendor

def index(request):
    return render(request, 'otgweb/index.html')

def events(request):
    events = Event.objects.order_by('-start_time')
    context = {'events': events}
    return render(request, 'otgweb/events.html', context)

def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    context = {'event': event}
    return render(request, 'otgweb/event_detail.html', context)

def vendors(request):
    now = timezone.now()
    recent = now - timedelta(days=30)

    vendors = Vendor.objects.all().annotate(num_recent_events=Sum(
        Case(
            When(membership__event__start_time__lte=now, membership__event__start_time__gte=recent, then=1),
            default=0, output_field=IntegerField()
        )
    )).order_by('-num_recent_events')

    context = {'vendors': vendors}
    return render(request, 'otgweb/vendors.html', context)

def vendor_detail(request, vendor_id):
    vendor = get_object_or_404(Vendor, pk=vendor_id)

    now = timezone.now()
    recent = now - timedelta(days=30)
    num_recent_events = vendor.event_set.filter(membership__event__start_time__lte=now, membership__event__start_time__gte=recent).count()

    context = {'vendor': vendor, 'num_recent_events': num_recent_events}
    return render(request, 'otgweb/vendor_detail.html', context)

otgweb/templates/otgweb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OTG - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'otgweb/styles.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'otgweb:index' %}">Off The Grid</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'otgweb:events' %}">Events</a></li>
            <li><a href="{% url 'otgweb:vendors' %}">Vendors</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      {% block body_block %}{% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

otgweb/templates/otgweb/event_detail.html
{% extends 'otgweb/base.html' %}

{% block title %}Event Detail{% endblock %}

{% block body_block %}
  <div class="page-header">
    <h1>{{ event.name }}</h1>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Event info</h3>
    </div>
    <div class="panel-body">
      <p>Description: {{ event.description }}</p>
      <p>Start time: {{ event.start_time }}</p>
    </div>
  </div>

  <h4>Vendors</h4>
  {% if event.vendors.all %}
    <ul class="list-group">
    {% for vendor in event.vendors.all %}
      <li class="list-group-item">
        <a href="{% url 'otgweb:vendor_detail' vendor.id %}">{{ vendor.name }}</a>
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <div class="alert alert-warning" role="alert">No vendor info for this event.</div>
  {% endif %}
{% endblock %}

otgweb/templates/otgweb/events.html
{% extends 'otgweb/base.html' %}

{% block title %}Events{% endblock %}

{% block body_block %}
  <div class="page-header">
    <h1>Events</h1>
  </div>

  <div class="well">
    <p>Here is the list of upcoming and previous OtG events. Data is updated every 6 hours.</p>
  </div>

  {% if events %}
    <ul class="list-group">
    {% for event in events %}
      <li class="list-group-item">
        <a href="{% url 'otgweb:event_detail' event.id %}">{{ event.name }} - {{ event.start_time }}</a>
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <div class="alert alert-warning" role="alert">No events currently available.</div>
  {% endif %}
{% endblock %}

otgweb/templates/otgweb/index.html
{% extends 'otgweb/base.html' %}

{% block title %}Index{% endblock %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Hello, food truck lovers!</h1>
    <p>This site lists out upcoming Off the Grid events and vendors.</p>
    <p>
      <a class="btn btn-primary btn-lg" href="{% url 'otgweb:events' %}" role="button">Show me events</a>
      <a class="btn btn-secondary btn-lg" href="{% url 'otgweb:vendors' %}" role="button">Show me vendors</a>
    </p>
  </div>
{% endblock %}

otgweb/templates/otgweb/vendor_detail.html
{% extends 'otgweb/base.html' %}

{% block title %}Vendor Detail{% endblock %}

{% block body_block %}
  <div class="page-header">
    <h1>{{ vendor.name }}</h1>
  </div>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Vendor info</h3>
    </div>
    <div class="panel-body">
      <p>Number of recent events: {{ num_recent_events }}</p>
    </div>
  </div>


  <h4>Events</h4>
  {% if vendor.event_set.all %}
    <ul class="list-group">
    {% for event in vendor.event_set.all %}
      <li class="list-group-item">
        <a href="{% url 'otgweb:event_detail' event.id %}">{{ event.name }} - {{ event.start_time }}</a>
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <div class="alert alert-warning" role="alert">No event info for this vendor.</div>
  {% endif %}
{% endblock %}

otgweb/templates/otgweb/vendors.html
{% extends 'otgweb/base.html' %}

{% block title %}Vendors{% endblock %}

{% block body_block %}
  <div class="page-header">
    <h1>Vendors</h1>
  </div>

  <div class="well">
    <p>Here is the list of OtG vendors, sorted by number of events attended in the past 30 days. Data is updated every 6 hours.</p>
  </div>

  {% if vendors %}
    <ul class="list-group">
    {% for vendor in vendors %}
      <li class="list-group-item">
        <a href="{% url 'otgweb:vendor_detail' vendor.id %}">{{ vendor.name }}</a>
        <span class="badge">{{ vendor.num_recent_events }}</span>
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <div class="alert alert-warning" role="alert">No vendors currently available.</div>
  {% endif %}
{% endblock %}